### ISSUE TITLE
when clicking "search again" from an error screen or otherwise make sure it scrolls to the bottom of the home page where the search bar is

### ISSUE THREAD

**Issue by teykamp** [teykamp/portfolio_display#147]
![image](https://user-images.githubusercontent.com/46391052/187487048-d53fd888-76ef-4366-a670-e92745f14311.png)
currently this button lands on the top of the page and users have to scroll back down to the search button

**Comment by Yonava** [comment]
adding issues! lezz go, back on the portfolio gridset!

**Comment by Yonava** [comment]
oops didnt mean to close
