### ISSUE TITLE
Add component in edit screen not working on wide screens

### ISSUE THREAD

**Issue by teykamp** [teykamp/portfolio_display#148]
SHOWN
![image](https://user-images.githubusercontent.com/46391052/187489321-f2bf83bf-e469-4646-9098-74a3ec757317.png)
 

EXPECTED:
![image](https://user-images.githubusercontent.com/46391052/187489390-2a56960a-0843-4f61-a025-9fbfba9ab45d.png)

I believe I am using an extra large screen, however the option to drag components is not visible. Replicated 3x on reload/relog.

**Comment by teykamp** [comment]
Problem can be solved by shrinking the screen as shown

**Comment by Yonava** [comment]
bug fixed in latest release
